// 앱 전체에서 공유하는 목 소비 기록 데이터
// API 연동 시 이 파일을 실제 fetch 로직으로 교체

import type { SpendingRecord } from '@/components/DayModal'

// SpendingRecord를 확장한 전체 기록 타입 (상세 화면, 회고 등에 사용)
export type FullRecord = SpendingRecord & {
  emotionTemp: number       // 0~100, step4에서 설정한 감정 온도
  memo: string              // 메모 (없으면 빈 문자열)
  rating: number | null     // 1~5 별점 (회고 완료 시), 없으면 null
  reviewReason: string | null // 회고 이유 칩 선택 값, 없으면 null
}

export const MOCK_RECORDS: FullRecord[] = [
  // ── 회고 미완료 (3일+ 경과) ─────────────────────────────────
  {
    id: '1',
    title: '말차 아인슈페너',
    category: '카페·편의점',
    date: '2026-05-10',
    photo: null,
    keyword: '소확행',
    amount: 7500,
    reviewDone: false,
    emotionTemp: 82,
    memo: '오늘 하루의 작은 위로였어',
    rating: null,
    reviewReason: null,
  },
  {
    id: '2',
    title: '',
    category: '외식·배달',
    date: '2026-04-20',
    photo: null,
    keyword: '충동적 소비',
    amount: 25000,
    reviewDone: false,
    emotionTemp: 22,
    memo: '',
    rating: null,
    reviewReason: null,
  },
  {
    id: '3',
    title: '',
    category: '패션잡화',
    date: '2026-04-10',
    photo: null,
    keyword: '충동적 소비',
    amount: 89000,
    reviewDone: false,
    emotionTemp: 18,
    memo: '',
    rating: null,
    reviewReason: null,
  },
  // ── 회고 완료 ────────────────────────────────────────────────
  // 같은 날짜 여러 기록 (2026-05-08에 3개 — 캐러셀 테스트용)
  {
    id: '4',
    title: '편의점 간식',
    category: '카페·편의점',
    date: '2026-05-08',
    photo: null,
    keyword: '합리적 소비',
    amount: 4800,
    reviewDone: true,
    emotionTemp: 72,
    memo: '',
    rating: 4,
    reviewReason: '가격 대비 좋았어요',
  },
  {
    id: '4b',
    title: '점심',
    category: '외식·배달',
    date: '2026-05-08',
    photo: null,
    keyword: '소확행',
    amount: 12000,
    reviewDone: true,
    emotionTemp: 85,
    memo: '친구랑 맛있게 먹었다',
    rating: 5,
    reviewReason: '좋은 경험이었어요',
  },
  {
    id: '4c',
    title: '',
    category: '문화생활',
    date: '2026-05-08',
    photo: null,
    keyword: '보상심리',
    amount: 35000,
    reviewDone: true,
    emotionTemp: 58,
    memo: '',
    rating: 3,
    reviewReason: '딱 그만큼이었어요',
  },
  {
    id: '5',
    title: '',
    category: '카페·편의점',
    date: '2026-05-06',
    photo: null,
    keyword: '소확행',
    amount: 6000,
    reviewDone: true,
    emotionTemp: 90,
    memo: '',
    rating: 5,
    reviewReason: '나에게 필요한 소비였어요',
  },
  {
    id: '6',
    title: '',
    category: '패션잡화',
    date: '2026-05-03',
    photo: null,
    keyword: '충동적 소비',
    amount: 52000,
    reviewDone: true,
    emotionTemp: 20,
    memo: '반성..',
    rating: 2,
    reviewReason: '충동적인 소비였어요',
  },
  {
    id: '7',
    title: '',
    category: '문화생활',
    date: '2026-05-01',
    photo: null,
    keyword: '합리적 소비',
    amount: 60000,
    reviewDone: true,
    emotionTemp: 70,
    memo: '',
    rating: 4,
    reviewReason: '좋은 경험이었어요',
  },
  {
    id: '8',
    title: '서점',
    category: '문화생활',
    date: '2026-05-15',
    photo: null,
    keyword: '소확행',
    amount: 18000,
    reviewDone: true,
    emotionTemp: 88,
    memo: '좋은 책 발견!',
    rating: 5,
    reviewReason: '나에게 필요한 소비였어요',
  },
  // ── 오늘(2026-05-26) 기록 — 홈 바구니 테스트용 ─────────────────
  {
    id: 'today-1',
    title: '아메리카노',
    category: '카페·편의점',
    date: '2026-05-27',
    photo: null,
    keyword: '소확행',
    amount: 4500,
    reviewDone: false,
    emotionTemp: 78,
    memo: '',
    rating: null,
    reviewReason: null,
  },
  {
    id: 'today-2',
    title: '점심',
    category: '외식·배달',
    date: '2026-05-26',
    photo: null,
    keyword: '합리적 소비',
    amount: 9000,
    reviewDone: false,
    emotionTemp: 70,
    memo: '',
    rating: null,
    reviewReason: null,
  },
  {
    id: 'today-3',
    title: '',
    category: '패션잡화',
    date: '2026-05-26',
    photo: null,
    keyword: '충동적 소비',
    amount: 38000,
    reviewDone: false,
    emotionTemp: 20,
    memo: '',
    rating: null,
    reviewReason: null,
  },
  // ── 키워드 아이콘 테스트용 추가 데이터 ──────────────────────────
  {
    id: '9',
    title: '야식',
    category: '외식·배달',
    date: '2026-05-18',
    photo: null,
    keyword: '스트레스',
    amount: 32000,
    reviewDone: false,
    emotionTemp: 28,
    memo: '야근 후 스트레스로 시켰다',
    rating: null,
    reviewReason: null,
  },
  {
    id: '10',
    title: '',
    category: '패션잡화',
    date: '2026-05-20',
    photo: null,
    keyword: '잘 모르겠어요',
    amount: 45000,
    reviewDone: false,
    emotionTemp: 50,
    memo: '',
    rating: null,
    reviewReason: null,
  },
  {
    id: '11',
    title: '헬스장 등록',
    category: '운동·건강',
    date: '2026-05-22',
    photo: null,
    keyword: '합리적 소비',
    amount: 80000,
    reviewDone: true,
    emotionTemp: 75,
    memo: '꾸준히 다녀야지',
    rating: 4,
    reviewReason: '가격 대비 좋았어요',
  },
  {
    id: '12',
    title: '향수',
    category: '패션잡화',
    date: '2026-05-23',
    photo: null,
    keyword: '보상심리',
    amount: 120000,
    reviewDone: false,
    emotionTemp: 65,
    memo: '열심히 일한 나에게 주는 선물',
    rating: null,
    reviewReason: null,
  },
  {
    id: '13',
    title: '버블티',
    category: '카페·편의점',
    date: '2026-05-24',
    photo: null,
    keyword: '소확행',
    amount: 6500,
    reviewDone: false,
    emotionTemp: 80,
    memo: '',
    rating: null,
    reviewReason: null,
  },
  {
    id: '14',
    title: '',
    category: '외식·배달',
    date: '2026-05-25',
    photo: null,
    keyword: '충동적 소비',
    amount: 55000,
    reviewDone: false,
    emotionTemp: 15,
    memo: '후회된다',
    rating: null,
    reviewReason: null,
  },
]
